spring.application.name=user-service

springdoc.swagger-ui.path=/api-docs

#Datasource configuration
spring.datasource.url=jdbc:postgresql://localhost/users
spring.datasource.username=postgres
spring.datasource.password=1337
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update